services:
  # Base de Datos MySQL
  mysql-server:
    image: mysql:8.0
    container_name: donaton-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - donaton-network

  # Servidor de Calidad SonarQube
  sonarqube:
    image: sonarqube:lts-community
    container_name: donaton-sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    networks:
      - donaton-network

  # Broker de Mensajería para comunicación asíncrona
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: donaton-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - donaton-network
  
  # Microservicio de Donaciones
  donaton-donaciones:
    build:
      context: ./donaton-donaciones # Ruta a la carpeta del microservicio
      dockerfile: Dockerfile
    container_name: donaton-donaciones
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - mysql-server
      - rabbitmq
    networks:
      - donaton-network

# Definición de redes y volúmenes persistentes
networks:
  donaton-network:
    driver: bridge

volumes:
  mysql-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions: