services:
  donaton-logistica:
    build:
      context: ../../donaton-logistica
      dockerfile: Dockerfile
    container_name: donaton-logistica
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://donaton-mysql-logistica:3306/logistica_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password_123
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://donaton-eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=donaton-rabbitmq
    networks:
      - donaton-network

networks:
  donaton-network:
    external: true
