services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: donaton-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - donaton-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  donaton-network:
    external: true
