export interface CountryCode {
  code: string;
  flag: string;
  name: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: '+54', flag: '🇦🇷', name: 'Argentina' },
  { code: '+591', flag: '🇧🇴', name: 'Bolivia' },
  { code: '+55', flag: '🇧🇷', name: 'Brasil' },
  { code: '+56', flag: '🇨🇱', name: 'Chile' },
  { code: '+57', flag: '🇨🇴', name: 'Colombia' },
  { code: '+506', flag: '🇨🇷', name: 'Costa Rica' },
  { code: '+53', flag: '🇨🇺', name: 'Cuba' },
  { code: '+593', flag: '🇪🇨', name: 'Ecuador' },
  { code: '+503', flag: '🇸🇻', name: 'El Salvador' },
  { code: '+502', flag: '🇬🇹', name: 'Guatemala' },
  { code: '+504', flag: '🇭🇳', name: 'Honduras' },
  { code: '+52', flag: '🇲🇽', name: 'México' },
  { code: '+505', flag: '🇳🇮', name: 'Nicaragua' },
  { code: '+507', flag: '🇵🇦', name: 'Panamá' },
  { code: '+595', flag: '🇵🇾', name: 'Paraguay' },
  { code: '+51', flag: '🇵🇪', name: 'Perú' },
  { code: '+1', flag: '🇺🇸', name: 'Estados Unidos / Canadá' },
  { code: '+1-787', flag: '🇵🇷', name: 'Puerto Rico' },
  { code: '+1-809', flag: '🇩🇴', name: 'Rep. Dominicana' },
  { code: '+598', flag: '🇺🇾', name: 'Uruguay' },
  { code: '+58', flag: '🇻🇪', name: 'Venezuela' },
  { code: '+34', flag: '🇪🇸', name: 'España' },
  { code: '+49', flag: '🇩🇪', name: 'Alemania' },
  { code: '+33', flag: '🇫🇷', name: 'Francia' },
  { code: '+39', flag: '🇮🇹', name: 'Italia' },
  { code: '+44', flag: '🇬🇧', name: 'Reino Unido' },
  { code: '+81', flag: '🇯🇵', name: 'Japón' },
  { code: '+86', flag: '🇨🇳', name: 'China' },
  { code: '+91', flag: '🇮🇳', name: 'India' },
  { code: '+7', flag: '🇷🇺', name: 'Rusia' },
  { code: '+61', flag: '🇦🇺', name: 'Australia' },
  { code: '+27', flag: '🇿🇦', name: 'Sudáfrica' },
  { code: '+93', flag: '🇦🇫', name: 'Afganistán' },
  { code: '+355', flag: '🇦🇱', name: 'Albania' },
  { code: '+213', flag: '🇩🇿', name: 'Argelia' },
  { code: '+376', flag: '🇦🇩', name: 'Andorra' },
  { code: '+244', flag: '🇦🇴', name: 'Angola' },
  { code: '+966', flag: '🇸🇦', name: 'Arabia Saudita' },
  { code: '+374', flag: '🇦🇲', name: 'Armenia' },
  { code: '+43', flag: '🇦🇹', name: 'Austria' },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaiyán' },
  { code: '+973', flag: '🇧🇭', name: 'Bahréin' },
  { code: '+880', flag: '🇧🇩', name: 'Bangladés' },
  { code: '+32', flag: '🇧🇪', name: 'Bélgica' },
  { code: '+501', flag: '🇧🇿', name: 'Belice' },
  { code: '+229', flag: '🇧🇯', name: 'Benín' },
  { code: '+375', flag: '🇧🇾', name: 'Bielorrusia' },
  { code: '+387', flag: '🇧🇦', name: 'Bosnia y Herzegovina' },
  { code: '+359', flag: '🇧🇬', name: 'Bulgaria' },
  { code: '+226', flag: '🇧🇫', name: 'Burkina Faso' },
  { code: '+257', flag: '🇧🇮', name: 'Burundi' },
  { code: '+975', flag: '🇧🇹', name: 'Bután' },
  { code: '+238', flag: '🇨🇻', name: 'Cabo Verde' },
  { code: '+855', flag: '🇰🇭', name: 'Camboya' },
  { code: '+237', flag: '🇨🇲', name: 'Camerún' },
  { code: '+974', flag: '🇶🇦', name: 'Catar' },
  { code: '+235', flag: '🇹🇩', name: 'Chad' },
  { code: '+357', flag: '🇨🇾', name: 'Chipre' },
  { code: '+850', flag: '🇰🇵', name: 'Corea del Norte' },
  { code: '+82', flag: '🇰🇷', name: 'Corea del Sur' },
  { code: '+225', flag: '🇨🇮', name: 'Costa de Marfil' },
  { code: '+385', flag: '🇭🇷', name: 'Croacia' },
  { code: '+45', flag: '🇩🇰', name: 'Dinamarca' },
  { code: '+20', flag: '🇪🇬', name: 'Egipto' },
  { code: '+971', flag: '🇦🇪', name: 'Emiratos Árabes' },
  { code: '+421', flag: '🇸🇰', name: 'Eslovaquia' },
  { code: '+386', flag: '🇸🇮', name: 'Eslovenia' },
  { code: '+372', flag: '🇪🇪', name: 'Estonia' },
  { code: '+251', flag: '🇪🇹', name: 'Etiopía' },
  { code: '+63', flag: '🇵🇭', name: 'Filipinas' },
  { code: '+358', flag: '🇫🇮', name: 'Finlandia' },
  { code: '+995', flag: '🇬🇪', name: 'Georgia' },
  { code: '+233', flag: '🇬🇭', name: 'Ghana' },
  { code: '+30', flag: '🇬🇷', name: 'Grecia' },
  { code: '+592', flag: '🇬🇾', name: 'Guyana' },
  { code: '+509', flag: '🇭🇹', name: 'Haití' },
  { code: '+36', flag: '🇭🇺', name: 'Hungría' },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia' },
  { code: '+98', flag: '🇮🇷', name: 'Irán' },
  { code: '+964', flag: '🇮🇶', name: 'Irak' },
  { code: '+353', flag: '🇮🇪', name: 'Irlanda' },
  { code: '+354', flag: '🇮🇸', name: 'Islandia' },
  { code: '+972', flag: '🇮🇱', name: 'Israel' },
  { code: '+1-876', flag: '🇯🇲', name: 'Jamaica' },
  { code: '+962', flag: '🇯🇴', name: 'Jordania' },
  { code: '+7', flag: '🇰🇿', name: 'Kazajistán' },
  { code: '+254', flag: '🇰🇪', name: 'Kenia' },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait' },
  { code: '+856', flag: '🇱🇦', name: 'Laos' },
  { code: '+371', flag: '🇱🇻', name: 'Letonia' },
  { code: '+961', flag: '🇱🇧', name: 'Líbano' },
  { code: '+218', flag: '🇱🇾', name: 'Libia' },
  { code: '+370', flag: '🇱🇹', name: 'Lituania' },
  { code: '+352', flag: '🇱🇺', name: 'Luxemburgo' },
  { code: '+261', flag: '🇲🇬', name: 'Madagascar' },
  { code: '+60', flag: '🇲🇾', name: 'Malasia' },
  { code: '+223', flag: '🇲🇱', name: 'Malí' },
  { code: '+356', flag: '🇲🇹', name: 'Malta' },
  { code: '+212', flag: '🇲🇦', name: 'Marruecos' },
  { code: '+230', flag: '🇲🇺', name: 'Mauricio' },
  { code: '+373', flag: '🇲🇩', name: 'Moldavia' },
  { code: '+377', flag: '🇲🇨', name: 'Mónaco' },
  { code: '+976', flag: '🇲🇳', name: 'Mongolia' },
  { code: '+382', flag: '🇲🇪', name: 'Montenegro' },
  { code: '+258', flag: '🇲🇿', name: 'Mozambique' },
  { code: '+95', flag: '🇲🇲', name: 'Myanmar' },
  { code: '+264', flag: '🇳🇦', name: 'Namibia' },
  { code: '+977', flag: '🇳🇵', name: 'Nepal' },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria' },
  { code: '+47', flag: '🇳🇴', name: 'Noruega' },
  { code: '+64', flag: '🇳🇿', name: 'Nueva Zelanda' },
  { code: '+968', flag: '🇴🇲', name: 'Omán' },
  { code: '+31', flag: '🇳🇱', name: 'Países Bajos' },
  { code: '+92', flag: '🇵🇰', name: 'Pakistán' },
  { code: '+48', flag: '🇵🇱', name: 'Polonia' },
  { code: '+351', flag: '🇵🇹', name: 'Portugal' },
  { code: '+40', flag: '🇷🇴', name: 'Rumania' },
  { code: '+250', flag: '🇷🇼', name: 'Ruanda' },
  { code: '+685', flag: '🇼🇸', name: 'Samoa' },
  { code: '+378', flag: '🇸🇲', name: 'San Marino' },
  { code: '+221', flag: '🇸🇳', name: 'Senegal' },
  { code: '+381', flag: '🇷🇸', name: 'Serbia' },
  { code: '+65', flag: '🇸🇬', name: 'Singapur' },
  { code: '+963', flag: '🇸🇾', name: 'Siria' },
  { code: '+252', flag: '🇸🇴', name: 'Somalia' },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka' },
  { code: '+249', flag: '🇸🇩', name: 'Sudán' },
  { code: '+46', flag: '🇸🇪', name: 'Suecia' },
  { code: '+41', flag: '🇨🇭', name: 'Suiza' },
  { code: '+597', flag: '🇸🇷', name: 'Surinam' },
  { code: '+66', flag: '🇹🇭', name: 'Tailandia' },
  { code: '+886', flag: '🇹🇼', name: 'Taiwán' },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania' },
  { code: '+992', flag: '🇹🇯', name: 'Tayikistán' },
  { code: '+670', flag: '🇹🇱', name: 'Timor Oriental' },
  { code: '+228', flag: '🇹🇬', name: 'Togo' },
  { code: '+676', flag: '🇹🇴', name: 'Tonga' },
  { code: '+1-868', flag: '🇹🇹', name: 'Trinidad y Tobago' },
  { code: '+216', flag: '🇹🇳', name: 'Túnez' },
  { code: '+90', flag: '🇹🇷', name: 'Turquía' },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistán' },
  { code: '+380', flag: '🇺🇦', name: 'Ucrania' },
  { code: '+256', flag: '🇺🇬', name: 'Uganda' },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistán' },
  { code: '+678', flag: '🇻🇺', name: 'Vanuatu' },
  { code: '+379', flag: '🇻🇦', name: 'Ciudad del Vaticano' },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam' },
  { code: '+967', flag: '🇾🇪', name: 'Yemen' },
  { code: '+260', flag: '🇿🇲', name: 'Zambia' },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabue' }
].sort((a, b) => a.name.localeCompare(b.name));
